USE [master]
GO

/****** Object:  Database [DBBudget_2]    Script Date: 15/11/2024 15:01:06 ******/
CREATE DATABASE [DBBudget_2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBBudget', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\DBBudget_2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBBudget_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\DBBudget_log_2.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DBBudget_2] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBBudget_2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBBudget_2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBBudget_2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBBudget_2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBBudget_2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBBudget_2] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBBudget_2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBBudget_2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBBudget_2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBBudget_2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBBudget_2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBBudget_2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBBudget_2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBBudget_2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBBudget_2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBBudget_2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBBudget_2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBBudget_2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBBudget_2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBBudget_2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBBudget_2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBBudget_2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBBudget_2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBBudget_2] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBBudget_2] SET  MULTI_USER 
GO

ALTER DATABASE [DBBudget_2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBBudget_2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBBudget_2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBBudget_2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBBudget_2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBBudget_2] SET QUERY_STORE = OFF
GO

USE [DBBudget_2]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DBBudget_2] SET  READ_WRITE 
GO


