CREATE TABLE FILE_IMPORTER_GROUP (
    FILE_TAG        VARCHAR2(20) NOT NULL,
    INPUT_PATH      VARCHAR2(100) NOT NULL,
    IS_ACTIVE       CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_FILE_IMPORTER_GROUP PRIMARY KEY (FILE_TAG)
);