CREATE TABLE FILE_IMPORTER_GROUP_EXT (
    FILE_TAG        VARCHAR2(20) NOT NULL,
    EXTENSION      VARCHAR2(20) NOT NULL,
    IS_ACTIVE       CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_FILE_IMPORTER_GROUP_EXT PRIMARY KEY (FILE_TAG, EXTENSION)
);