CREATE TABLE FILE_IMPORTER_PROCESS (
    FILE_TAG        VARCHAR2(20) NOT NULL,
    SP_NAME			VARCHAR2(100), 
	FIXED_W 		CHAR(1) DEFAULT 'N' NOT NULL, 
	CHAR_SEPARATION CHAR(1),
	IS_ACTIVE       CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_FILE_IMPORTER_PROCESS PRIMARY KEY (FILE_TAG)
);