CREATE TABLE FILE_IMPORTER_FILE (
    FILE_TAG        VARCHAR2(20) NOT NULL,
    FILE_NAME		VARCHAR2(100), 
	D_MODIFICATION 	DATE,
	D_PROCESS	 	DATE,	
	FILE_ID			NUMBER,
	PROCESSED		CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_FILE_IMPORTER_FILE PRIMARY KEY (FILE_ID, FILE_TAG)
);