CREATE TABLE FILE_IMPORTER_FILE_DET (
	FILE_ID			NUMBER NOT NULL,
	FILE_DET_ID		NUMBER NOT NULL,
	D_PROCESS	 	DATE,	
    ROW_N			NUMBER,
	ROW_TEXT		VARCHAR2(2000),
	PROCESSED		CHAR(1) DEFAULT 'N' NOT NULL,	
    CONSTRAINT PK_FILE_IMPORTER_FILE_DET PRIMARY KEY (FILE_ID, FILE_DET_ID)
);