CREATE TABLE FILE_IMPORTER_MAP (
	FILE_TAG        VARCHAR2(20) NOT NULL,
	FIELD_NUM		NUMBER NOT NULL,
	FIELD_NAME		VARCHAR2(50),
	HOME_COL		NUMBER,
	FINAL_COL		NUMBER,
	CONSTRAINT PK_FILE_IMPORTER_MAP PRIMARY KEY (FILE_TAG, FIELD_NUM)
);